[project]
name = "onagigawa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[project.scripts]
# package.module:func
onagigawa= "onagigawa:main"
[tool.pyright]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.uv]
package = true

[dependency-groups]
dev = [
    "pyright>=1.1.406",
]
