[project]
name = "onagigawa"
version = "0.0.1"
description = "Pull request drafter"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
]

[project.scripts]
# package.module:func
# onagigawa = "onagigawa:main"
[tool.pyright]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "black>=25.9.0",
    "ipython>=9.6.0",
    "pip>=25.2",
    "pyright>=1.1.406",
]
